### ISSUE TITLE
navigateFallbackWhiteList

### ISSUE THREAD

**Issue by wuzzeb** [cyyyu/parcel-plugin-sw-precache#12]
sw-precache requires navigateFallbackWhiteList to be an array of regexes, but when specifying the option in package.json it is an array of strings.  I am trying in package.json to put

~~~
{
  ...
  "sw-precache": {
    "navigateFallback": "index.html",
    "navigateFallbackWhitelist": [
      "^(?!\/swagger\/).*"
    ]
  }
}
~~~

It is somewhat annoying because the regex is just converted back to a string in sw-precache here https://github.com/GoogleChromeLabs/sw-precache/blob/master/lib/sw-precache.js#L307 but because of the call to `source`, the setting must be a regex and not a string.

parcel-plugin-sw-precache should convert the strings from pacakge.json into regexes.  (Looking through the options for sw-precache, there are several other settings that also require regexes.)

**Comment by cyyyu** [comment]
Will look into it.

**Comment by cyyyu** [comment]
Try v1.0.1
Hope it works for you.

**Comment by wuzzeb** [comment]
Yes, just tested it and it works.  Thanks!
