### ISSUE TITLE
`Unexpected token` error on build

### ISSUE THREAD

**Issue by dsinni** [cyyyu/parcel-plugin-sw-precache#13]
I'm receiving the following error upon build, using Parcel `1.9.7`:

Some directory names have been changed to `XXXXXX` to protect the innocent.

```js
‼  Unexpected token ...
      ...swPrecacheConfigs
      ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (C:\XXXXXX\parcel-sw-precache\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\XXXXXX\parcel-sw-precache\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (C:\XXXXXX\parcel-sw-precache\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at localRequire (C:\XXXXXX\parcel-sw-precache\node_modules\parcel-bundler\src\utils\localRequire.js:28:10)
    at <anonymous>
```

**Comment by cyyyu** [comment]
ops...

Should be a issue on your nodejs.

Which version of node are you using? The `...` syntax is supposed to be supported by node@6.x and later if Im correct.

**Comment by dsinni** [comment]
Hi, @cyyyu. Thanks for the speedy reply.

I'm using Node `8.2.1`.

**Comment by cyyyu** [comment]
Not sure what's going on there.

Can you provide reproduction steps or a minimal repo to reproduce it?

**Comment by dsinni** [comment]
Honestly, not doing much. Installed the following `devDependencies`:

```js
    "parcel-bundler": "^1.9.7",
    "parcel-plugin-sw-precache": "^1.0.1"
```

And then ran my `npm run build` script which in turn runs `parcel build src/index.html -d dist --no-source-maps`.

Is a manifest file required before build?

**Comment by cyyyu** [comment]
Tried as you did and it works well for me.

I believe it can be addressed by upgrading nodejs. Can you try that? Make it v10.0.0 or latest version.

**Comment by cyyyu** [comment]
Looks similiar to https://github.com/Esri/jsapi-resources/issues/131

**Comment by dsinni** [comment]
Okay. It's pretty late here now, but I'll give that a shot tomorrow and let you know how it goes.

Thanks again.

**Comment by dsinni** [comment]
Hi, @cyyyu.

I updated to the latest Node (`10.10.0`) and it builds now. Now I just need to see how the service worker works, but that is another thing completely and I'm sure it works well.

Thanks for your help. I'll close the issue.

**Comment by cyyyu** [comment]
Cool. Feel free to ask more questions.

**Comment by dsinni** [comment]
Thank you, sir.

**Comment by dsinni** [comment]
I hope you don't mind me asking here, but I don't see the `service-worker.js` file being referenced anywhere. Does it still need to be added to `index.html` manually?

**Comment by cyyyu** [comment]
you don't need to put in index.html.

Take a look https://github.com/cyyyu/parcel-plugin-sw-precache/issues/4

**Comment by dsinni** [comment]
Thanks, @cyyyu. I'll comment further on that issue.
