### ISSUE TITLE
staticFileGlobsIgnorePatterns inside package.json being ignored

### ISSUE THREAD

**Issue by pocesar** [cyyyu/parcel-plugin-sw-precache#16]
this option inside package.json:

```json
  "sw-precache": {
    "staticFileGlobsIgnorePatterns": [
      "/report.html"
    ]
  },
```

seems to not be working

**Comment by cyyyu** [comment]
I forgot to add it here: https://github.com/cyyyu/parcel-plugin-sw-precache/blob/master/index.js#L19

Would you like to make a pr?

**Comment by pocesar** [comment]
done
