### ISSUE TITLE
Support Large dist file

### ISSUE THREAD

**Issue by swift1911** [cyyyu/parcel-plugin-sw-precache#2]
When i use parcel with --no-minify development,my js file is larger than 2.1MB
It shows:

![image](https://user-images.githubusercontent.com/9301003/38463806-47ed502a-3b35-11e8-9ca3-18b11d0e1ca1.png)

Is that any ways to support large js file?

**Comment by cyyyu** [comment]
This issue is `sw-precache` related who skips files larger than 2mb.
But for sure you should be able to configure that. 
So, I have implemented a feature for full configurations support.
Check out the latest version(0.4.0) and do as follows.
Try it out and feedbacks are always welcome :)
```
{
  "name": "my-project",
  "version": "0.1.0",
  ...

  // my sw-precache configs
  "sw-precache": {
    "maximumFileSizeToCacheInBytes": 10485760
  }
}
```

**Comment by swift1911** [comment]
ok，it works
