### ISSUE TITLE
Absolute paths are used in 'precacheConfig'

### ISSUE THREAD

**Issue by uwolfer** [cyyyu/parcel-plugin-sw-precache#3]
Generated file contains absolute paths:
``
var precacheConfig=[["/512x512.8ed2a3a5.png","995b595601aa502081aad9db6df0c0ed"]
``

In my case, I'd like to get relative paths (using `parcel build index.html --public-url ./`):
``
var precacheConfig=[["512x512.8ed2a3a5.png","995b595601aa502081aad9db6df0c0ed"]
``

Changing [L27](https://github.com/cyyyu/parcel-plugin-sw-precache/blob/master/index.js#L27) to the following fixes the issue for me - but not sure if it is a proper fix:
``
stripPrefix: targetDir + '/',
``

Please also note: there are other absolute paths in your plugin like `navigateFallback`.

Using 0.4.0.

Thanks for this plugin! :)

**Comment by cyyyu** [comment]
@uwolfer You may want to take a look at the related pr.
It provides you the ability to set `replacePrefix` to achieve your will.
In your case you can do as follows in your `package.json`
```
{
  "sw-precache": {
     "replacePrefix": ""
  }
}
```
Let me know if it solves your problem.

**Comment by uwolfer** [comment]
@cyyyu: Thanks, this fix works for me.

Just wondering if it would be possible to respect `--public-url` parameter for this which would follow the zero-configuration approach.

**Comment by cyyyu** [comment]
@uwolfer Yea it should be. 😄 

I m going to patch 0.4.1 to do that.

**Comment by cyyyu** [comment]
@uwolfer  released 0.4.1 now.

you don't need `replacePrefix` at all. try it out and let me know if it works or not :)
