### ISSUE TITLE
Adding script tag for production build?

### ISSUE THREAD

**Issue by gorbypark** [cyyyu/parcel-plugin-sw-precache#8]
I am having some trouble actually including the service worker in my project.  I can see the generated service-worker.js show up in the dist/ folder, but how do I go about actually including it?  If I <script src="dist/service-worker.js"></script> in my index.html, the build obviously fails the first time (and in CI since the build is 'fresh' every time) because service-worker.js does not exist yet.

**Comment by cyyyu** [comment]
How do you serve your static files (js,css, etc)? 
You need do the same for the `service-worker.js` file and make sure the endpoint is `/service-worker.js`
Furthermore, you need to register the service worker, use the endpoint above. 
This is not related to this repo. Take a look at this: https://github.com/cyyyu/firetodo/blob/master/src/register-service-worker.ts#L25

**Comment by gorbypark** [comment]
service-worker.js is available at the endpoint `/server-worker.js`, but I need to actually point to it in my index.html don't I?  Such as <script src="service-worker.js"></script>?  If I don't point to it, it doesn't seem to load/be registered, but if I do point to it, parcel tries to find the file before it is generated and produces an error.
```
 /Users/blah/Documents/Code/blah/index.html: Cannot resolve dependency './service-worker.js' at ' /Users/blah/Documents/Code/blah/index.html' at Resolver.resolve (/Users/blah/Documents/Code/blah/node_modules/parcel-bundler/src/Resolver.js:70:17)
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by cyyyu** [comment]
you don't need to point into index.html.
just to the same as I did in https://github.com/cyyyu/firetodo/blob/master/src/register-service-worker.ts

service worker is actually registered here:
![image](https://user-images.githubusercontent.com/15100664/40469986-c8dc9bf2-5f64-11e8-898a-41ef310f1287.png)

**Comment by gorbypark** [comment]
Ah, ok!  Do you have a non-type script example perhaps?

**Comment by cyyyu** [comment]
I feel there is no ts features in that file. just rename to js and it should work.

**Comment by gorbypark** [comment]
Thanks.
